/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <cstdint>
#include "./Logging.h"

//==============================================================================
DAWTestAudioProcessor::DAWTestAudioProcessor()
{
	UserParams[Volume] = 1.0f; //default volume 1.0 (no change)
	mBrainController.SetVolume(UserParams[Volume]); //push VST default to effect
	UserParams[Beat] = (1); //default beat 1/15 (no change)
	mBrainController.SetBeat(UserParams[Beat]); //push VST default to effect
	UserParams[Key] = 0; //default frequency 500Hz (no change)
	mBrainController.SetKey(UserParams[Key]); //push VST default to effect
    UIUpdateFlag=true; //Request UI update
	noteOffMidiFlag = false;
}

DAWTestAudioProcessor::~DAWTestAudioProcessor()
{
}

int DAWTestAudioProcessor::getNumParameters(){ return totalNumParam; }

float DAWTestAudioProcessor::getParameter (int index) {
	switch (index) {
		case Volume://example update from internal
			UserParams[Volume] = mBrainController.GetVolume();
			return UserParams[Volume];
		case Beat://example update from internal
			return UserParams[Beat];
		case Key://example update from internal
			UserParams[Key] = mBrainController.GetKey();
			return UserParams[Key];
        default: return 0.0f;//invalid index
    }
}

void DAWTestAudioProcessor::setParameter (int index, float newValue) {
	switch (index) {
		case Volume:
			UserParams[Volume] = newValue;
			mBrainController.SetVolume(UserParams[Volume]);
			break;
		case Beat:
			UserParams[Beat] = newValue;
			mBrainController.SetBeat((int)newValue);
			/* Beats:
				1/16: 1
				1/8: 2
				1/4: 3
			*/

#ifdef WIN32
			LOG("Beat updated to " + std::to_string((int)newValue));
#endif
			break;
		case Key:
			UserParams[Key] = newValue;
			mBrainController.SetKey((int)newValue);
			/* Keys:
				Key of C: 1
				Key of Db / C#: 2
				Key of D: 3
				Key of Eb / D#: 4
				Key of E: 5
				Key of F: 6
				Key of Gb / Key of F#: 7
				Key of G: 8
				Key of Ab / G#: 9
				Key of A: 10
				Key of Bb / A#: 11
				Key of B / Key of Cb: 12
			*/
			break;
		default: return;
    }
    UIUpdateFlag=true;//Request UI update -- Some OSX hosts use alternate editors, this updates ours
}

const String DAWTestAudioProcessor::getParameterName (int index) {
	switch (index) {
		case Volume: return "Volume";
		case Beat: return "Beat";
		case Key: return "Key";
        default:return String::empty;
    }
}

const String DAWTestAudioProcessor::getParameterText (int index) {
    if(index>=0 && index<totalNumParam)
        return String(UserParams[index]);//return parameter value as string
    else return String::empty;
}

//This is where all the audio processing happens
void DAWTestAudioProcessor::processBlock(AudioSampleBuffer& buffer, MidiBuffer& midiMessages) {
	if(getNumInputChannels()<2) {
    } else {
		bool isBeatTick = false;

		if (!midiMessages.isEmpty())
		{

			if (noteOffMidiFlag)
			{
				// Not a beat tick, so don't do anything
				noteOffMidiFlag = false;
			}
			else
			{
				isBeatTick = true;
				noteOffMidiFlag = true;

				// Perform FFT for pitch detection
				mInputProcessor.SetBlock(buffer);
				mInputProcessor.SetSampleRate(getSampleRate());
				mInputProcessor.AnalyseBlock();
				float currentFreq = mInputProcessor.GetFrequency();

				float note = currentFreq;

				// Perform analysis to determine which note should be played
				double noteForOutput = mBrainController.clockTickFrequency((double)currentFreq, isBeatTick, midiMessages);

				if (noteForOutput != 0)
				{
					mOutputController.PlayNote(noteForOutput, midiMessages, 0);
				}

				if (hasEditor())
				{
					AudioProcessorEditor *temp = getActiveEditor();
				}
			}
		}
    }
}

//Save UserParams/Data to file
void DAWTestAudioProcessor::getStateInformation (MemoryBlock& destData) {
    XmlElement root("Root");
	XmlElement *el;
	el = root.createNewChildElement("Volume");
	el->addTextElement(String(UserParams[Volume]));
	el = root.createNewChildElement("Beat");
	el->addTextElement(String(UserParams[Beat]));
	el = root.createNewChildElement("Key");
	el->addTextElement(String(UserParams[Key]));
    copyXmlToBinary(root,destData);
}
 
//Load UserParams/Data from file
void DAWTestAudioProcessor::setStateInformation (const void* data, int sizeInBytes) {
    XmlElement* pRoot = getXmlFromBinary(data,sizeInBytes);
    
    if(pRoot!=NULL) {
		forEachXmlChildElement((*pRoot), pChild) {
			if (pChild->hasTagName("Volume")) {
				String text = pChild->getAllSubText();
				setParameter(Volume, text.getFloatValue());
			} else if (pChild->hasTagName("Beat")) {
				String text = pChild->getAllSubText();
				setParameter(Beat, text.getFloatValue());
			} else if (pChild->hasTagName("Key")) {
				String text = pChild->getAllSubText();
				setParameter(Key, text.getFloatValue());
			}
        }
        delete pRoot;
        UIUpdateFlag=true;//Request UI update
    }
}

//==============================================================================
const String DAWTestAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

const String DAWTestAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String DAWTestAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool DAWTestAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool DAWTestAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool DAWTestAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool DAWTestAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool DAWTestAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double DAWTestAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int DAWTestAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int DAWTestAudioProcessor::getCurrentProgram()
{
    return 0;
}

void DAWTestAudioProcessor::setCurrentProgram (int index)
{
}

const String DAWTestAudioProcessor::getProgramName (int index)
{
    return String();
}

void DAWTestAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void DAWTestAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void DAWTestAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

//==============================================================================
bool DAWTestAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* DAWTestAudioProcessor::createEditor()
{
    return new DAWTestAudioProcessorEditor (*this);
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new DAWTestAudioProcessor();
}
